export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const INCREMENT_COUNTER_ASYNC = 'INCREMENT_COUNTER_ASYNC';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const SAGA_LOADING = 'SAGA_LOADING';
export const SAGA_SUCCESS = 'SAGA_SUCCESS';
export const SAGA_FAILURE = 'SAGA_FAILURE';

export const LOADING = "LOADING";
export const LOADED = "LOADED";


